api_platform:

    title: 'Maquequette'
    description: 'ou moncucul ?'
    version: '1.0.0'

    swagger:
         swagger_ui_extra_configuration:
           docExpansion: none

         api_keys:
             JWT:
                name: Authorization
                type: header