# app/config/config.yml

artprima_prometheus_metrics:
    # namespace is used to prefix the prometheus metrics
    namespace: maquequette

    # metrics backend
    storage:
        # Known values: in_memory, apcu, apcng, redis
        type: in_memory
        # Available parameters used by redis
        host: 127.0.0.1
        port: 6379
        timeout: 0.1
        read_timeout: 10
        persistent_connections: false
    # used to disable default application metrics
    disable_default_metrics: false
    # used to disable default metrics from promphp/prometheus_client_php
    disable_default_promphp_metrics: false
    # used to enable console metrics
    enable_console_metrics: false