controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_doc:
    path: /
    controller: api_platform.swagger_ui.action

auth_refresh:
    path: /auth/refresh
    
app_metrics:
    resource: '@ArtprimaPrometheusMetricsBundle/Resources/config/routing.xml'