version: '3'
services:
  prometheus:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image : grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml